# Generated by Django 3.1.2 on 2020-12-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='city',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
