# Generated by Django 3.1.2 on 2020-12-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0002_joblisting_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicant',
            name='applicant_email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='contracts',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='joborganization',
            name='company_email',
            field=models.CharField(max_length=50),
        ),
    ]
